/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const petstoreVersions = require("./docs/openAPI/petstore_versioned/versions.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils");
const sidebars = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: '用户',
      link: {
        type: 'generated-index',
        title: '用户',
        slug: 'user',
        description:
          "帮助用户快速完成个人设置",
        keywords: ['users'],
        // image: '/img/docusaurus.png',
      },
      items: [
        'user/user-sshkey',
        'user/user-verify',
        {
          type: 'category',
          label: 'Git',
          link: {
            type: 'generated-index',
            title: 'Git 入门',
            slug: 'git',
            keywords: ['git'],
          },
          items: [
            'user/git-install',
            'user/git-config',
            'user/git-quickstart',
            'user/git-advanced',
          ],
        },
        'user/pats',
      ],
    },
    {
      type: 'category',
      label: '代码库',
      link: {
        type: 'generated-index',
        title: '代码库',
        slug: 'repo',
        description:
          "代码库使用及设置",
        keywords: ['repos'],
      },
      items: [
        'repo/files',
        'repo/branch',
        'repo/tag',
        {
          type: 'category',
          label: '提交',
          link: {
            type: 'generated-index',
            title: '提交',
            slug: 'commit',
            keywords: ['commit'],
          },
          items: [
            'repo/commit',
            'repo/cherry-pick',
            'repo/revert',
          ],
        },
        'repo/change-request',
        // 'repo/issue',
        {
          type: 'category',
          label: 'Issue',
          link: {
            type: 'generated-index',
            title: 'Issue',
            slug: 'issue',
            keywords: ['issue'],
          },
          items: [
            'repo/issue',
            'repo/label',
            'repo/milestone',
          ],
        },
        'user/repo-members',
        'permission',
        {
          type: 'category',
          label: '代码库设置',
          link: {
            type: 'generated-index',
            title: '代码库设置',
            slug: 'repo-config',
            keywords: ['config'],
          },
          items: [
            'repo/repo-config',
            'repo/pr-config',
            'repo/br-config',
            'repo/push-rules',
            'webhooks',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '组织',
      link: {
        type: 'generated-index',
        title: '组织',
        slug: 'group',
        description:
          "组织使用及设置",
        keywords: ['orgs'],
      },
      items: [
        'org/new-org',
        'org/org-members',
        'org/org-settings',
      ],
    },
    {
      type: 'category',
      label: '用户协议',
      link: {
        type: 'generated-index',
        title: '用户协议',
        slug: 'terms',
        description:
          "AtomGit 平台用户使用协议",
        keywords: ['agreements'],
      },
      items: [
        'agreements/declare',
        'agreements/tos',
        'agreements/privacy',
      ],
    },
  ],
  api: [
    {
      type: "category",
      label: "开放接口",
      link: {
        type: "generated-index",
        title: "AtomGit OPEN API",
        description:
            "为了构建更好的AtomGit生态环境，我们推出了基于OAuth2的API版本。API接口使用方式以及Url都参照GitHub，为了各位开发者更好的兼容已经存在的第三方应用。",
        slug: "/category/api",
      },
      items: require("./docs/openAPI/api_versioned/sidebar.js"),
    },
   /* {
      type: "category",
      label: "Petstore",
      link: {
        type: "generated-index",
        title: "Petstore API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/petstore-api",
      },
      items: require("./docs/openAPI/petstore/sidebar.js"),
    },*/
 /*   {
      type: "category",
      label: "Cloud Object Storage",
      link: {
        type: "generated-index",
        title: "Cloud Object Storage API",
        slug: "/category/cos-api",
      },
      items: require("./docs/openAPI/cos/sidebar.js"),
    },
    {
      type: "category",
      label: "Burgers",
      link: {
        type: "generated-index",
        title: "Burger API",
        slug: "/category/food-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "openAPI/food/burgers", // '.' means the current docs folder
        },
      ],
    },*/
/*    {
      type: "category",
      label: "Yogurt Store",
      link: {
        type: "generated-index",
        title: "Yogurt Store API",
        slug: "/category/yogurt-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "openAPI/food/yogurtstore", // '.' means the current docs folder
        },
      ],
    },*/
  ],
  "petstore-2.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v2.0.0`),
    },
    {
      type: "category",
      label: "Petstore",
      link: {
        type: "generated-index",
        title: "Petstore API (latest)",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/petstore-versioned-api",
      },
      items: require("./docs/openAPI/petstore_versioned/sidebar.js"),
    },
  ],

  "petstore-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: "version-button",
    },
    {
      type: "html",
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: "category",
      label: "AtomGit-Api文档",
      link: {
        type: "generated-index",
        title: "AtomGit-Api文档(v1.0.0)",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/petstore-api-1.0.0",
      },
      items: require("./docs/openAPI/petstore_versioned/1.0.0/sidebar.js"),
    },
  ],
  oauth: [
    {
      type: 'autogenerated',
      dirName: 'oauth',
    },
  ],
};

module.exports = sidebars;
