/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        // 'installation',
        // 'configuration',
        // 'playground',
        // 'typescript-support',
      ],
    },
    {
      type: 'category',
      label: '用户',
      link: {
        type: 'generated-index',
        title: '使用文档-用户',
        description:
          "帮助用户快速完成个人设置",
        keywords: ['users'],
        // image: '/img/docusaurus.png',
      },
      items: [
        'user/user-sshkey',
        'user/user-verify',
      ],
    },
  ],
  oatuh: [
    {
      type: 'autogenerated',
      dirName: 'oatuh',
    },
  ],
};

module.exports = sidebars;